export { default as ARMSv1Mockup } from "./ARMSv1-Mockup.webp"
export { default as ARMSv2Mockup } from "./ARMSv2-Mockup.webp"
export { default as ARMSv3Mockup } from "./ARMSv3-Mockup.webp"
export { default as ClimateMockup } from "./Climate-Mockup.webp"
export { default as DaysbeyondMockup } from "./Daysbeyond-Mockup.webp"
export { default as SrinivasMockup } from "./SEM-Mockup.webp"
export { default as VortexaMockup } from "./Vortexa-Mockup.webp"
export { default as XreconMockup } from "./Xrecon-Mockup.webp"
export { default as YoatubeMockup } from "./Yoatube-Mockup.webp"

export { default as PlantDiseaseMockup } from "./plant_disease_mockup_1773157776292.png"
export { default as GestureTextMockup } from "./gesture_text_mockup_1773157842570.png"
export { default as BmiAnalyzerMockup } from "./bmi_analyzer_mockup_1773157903792.png"
export { default as CivicCircleMockup } from "./civic_circle_mockup_1773157975131.png"
export { default as ExamSeatingMockup } from "./exam_seating_mockup_1773158036661.png"
